### ISSUE TITLE
Support generation from unexported interfaces

### ISSUE THREAD

**Issue by sykesm** [maxbrunsfeld/counterfeiter#100]
The older versions of counterfeiter (as of #26) supported fakes generated from unexported interfaces. The new version (which is improved many ways) breaks that with the addition of the assignment of the generated fake to an unnamed var of the faked interface's type.

If the unnamed var assignment were omitted for unexported interfaces, the capability introduced with #26 would be restored.

**Comment by sykesm** [comment]
One possible implementation is #101.

**Comment by joefitzgerald** [comment]
Fixed in #100.
