### ISSUE TITLE
Go Mod Version not recognised

### ISSUE THREAD

**Issue by elgohr** [maxbrunsfeld/counterfeiter#114]
Using
`go mod tidy`
counterfeiter is reduced to
`require github.com/maxbrunsfeld/counterfeiter v0.0.0-20190111051351-d7285d544cff`
in go.mod

So v6.0.1 doesn't seem to be recognised

**Comment by dnephin** [comment]
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

I believe that's the problem. There are a few options to make it work.

**Comment by joefitzgerald** [comment]
This should be fixed in `v6.0.2`. Note however that the README instructions require https://github.com/myitcv/gobin/pull/70 to be merged to function correctly.
