### ISSUE TITLE
Support generating fakes of interfaces in modules

### ISSUE THREAD

**Issue by glyn** [maxbrunsfeld/counterfeiter#115]
When I have one Go module depending on another, it's useful to be able to generate fakes for an interface in the "other" module, particularly if I don't control the other module.

For example, the module `github.com/glyn/c1` depends on the module `github.com/glyn/c2` (these are real repositories, created to experiment with this issue). I can successfully generate fakes in c2 as usual:
```
// change directory to clone of c2
$ counterfeiter pkg Iface
Writing `FakeIface` to `pkg/pkgfakes/fake_iface.go`... Done
$ cat pkg/pkgfakes/fake_iface.go
// Code generated by counterfeiter. DO NOT EDIT.
package pkgfakes

import (
	sync "sync"

	pkg "github.com/glyn/c2/pkg"
)

type FakeIface struct {
// etc.
```

But how do I do this from c1? The following attempt doesn't work out well:
```
// cd to clone of c1
$ counterfeiter -p github.com/glyn/c2/pkg Iface
Writing `Pkg` to `pkgshim`... Done
$ cat pkgshim
// Code generated by counterfeiter. DO NOT EDIT.
package pkgshim

//
```
counterfeiter simply generates a file with a `package` statement, some comments, and some white space.

**Comment by joefitzgerald** [comment]
If you use `counterfeiter github.com/glyn/c2/pkg.Iface` (note the lack of the package `-p` flag, and the inclusion of the `.` between `pkg` and `Iface`), it will work.

**Comment by glyn** [comment]
It did indeed work. Thanks @joefitzgerald!

**Comment by glyn** [comment]
Submitted https://github.com/maxbrunsfeld/counterfeiter/pull/116 to provide minimal documentation for the secret syntax.
