### ISSUE TITLE
gobin vs go run

### ISSUE THREAD

**Issue by bobheadxi** [maxbrunsfeld/counterfeiter#119]
In the documentation, i noticed that the recommended go generate directive is:

```go
//go:generate gobin -m -run github.com/maxbrunsfeld/counterfeiter/v6 . MySpecialInterface
```

is there a reason to not use `go run` directly? I've been using the following without any issue:

```go
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . MySpecialInterface
```

with modules enabled it seems to run from the mod cache as expected. it might be nice to recommend `go run` instead of `gobin`, so that an additional tool does not need to be installed

**Comment by joefitzgerald** [comment]
It is my understanding that currently, `go run` will not use the version specified in the `go.mod` when invoked from a working directory inside a module, using an import path as an argument. Semantically it will operate like go get does; it will get the latest release or the most recent commit on master, unless a version is specified in the statement (I.e. `go run github.com/the/pkg@v1.2.3`), in which case you will need to keep that synchronized across all go generate statements that invoke the tool.

Using `gobin` for now will ensure you are working with a specific version as expressed in your go.mod file (and not specified in every go generate statement), which will ensure collaborators on your package also use the same version when running go generate, and ensure you have a single place to specify the version.

**Comment by bobheadxi** [comment]
> It is my understanding that currently, go run will not use the version specified in the go.mod when invoked from a working directory inside a module, using an import path as an argument

hm, here's a not-very-formal demo that I think it actually does, commands run in sequence:

#### binary uninstalled

```
~/go/src/github.com/RTradeLtd/Lens master
❯ which counterfeiter
/Users/robertlin/go/bin/counterfeiter

~/go/src/github.com/RTradeLtd/Lens master
❯ rm -rf /Users/robertlin/go/bin/counterfeiter

~/go/src/github.com/RTradeLtd/Lens master
❯ counterfeiter        
zsh: command not found: counterfeiter
```

#### nothing in gopath

```
~/go/src/github.com/RTradeLtd/Lens master
❯ ls $GOPATH/src/github.com/maxbrunsfeld/counterfeiter
LICENSE                 appveyor.yml            benchmark_test.go       generated_fakes_test.go go.mod                  integration             scripts
README.md               arguments               fixtures                generator               go.sum                  main.go

~/go/src/github.com/RTradeLtd/Lens master
❯ rm -rf $GOPATH/src/github.com/maxbrunsfeld/counterfeiter

~/go/src/github.com/RTradeLtd/Lens master
❯ ls $GOPATH/src/github.com/maxbrunsfeld/counterfeiter/v6 
ls: /Users/robertlin/go/src/github.com/maxbrunsfeld/counterfeiter/v6: No such file or directory

~/go/src/github.com/RTradeLtd/Lens master
❯ go generate ./...                           
package github.com/maxbrunsfeld/counterfeiter/v6: cannot find package "github.com/maxbrunsfeld/counterfeiter/v6" in any of:
        /usr/local/Cellar/go/1.12.4/libexec/src/github.com/maxbrunsfeld/counterfeiter/v6 (from $GOROOT)
        /Users/robertlin/go/src/github.com/maxbrunsfeld/counterfeiter/v6 (from $GOPATH)
analyzer/images/tensorflow.go:20: running "go": exit status 1
package github.com/maxbrunsfeld/counterfeiter/v6: cannot find package "github.com/maxbrunsfeld/counterfeiter/v6" in any of:
        /usr/local/Cellar/go/1.12.4/libexec/src/github.com/maxbrunsfeld/counterfeiter/v6 (from $GOROOT)
        /Users/robertlin/go/src/github.com/maxbrunsfeld/counterfeiter/v6 (from $GOPATH)
engine/engine.go:18: running "go": exit status 1
package github.com/maxbrunsfeld/counterfeiter/v6: cannot find package "github.com/maxbrunsfeld/counterfeiter/v6" in any of:
        /usr/local/Cellar/go/1.12.4/libexec/src/github.com/maxbrunsfeld/counterfeiter/v6 (from $GOROOT)
        /Users/robertlin/go/src/github.com/maxbrunsfeld/counterfeiter/v6 (from $GOPATH)
mocks/third_party.go:5: running "go": exit status 1
```

#### enable go modules

```
~/go/src/github.com/RTradeLtd/Lens master
❯ export GO111MODULE=on

~/go/src/github.com/RTradeLtd/Lens master
❯ go generate ./...    
Writing `FakeTensorflowAnalyzer` to `../../mocks/images.mock.go`... Done
Writing `FakeSearcher` to `../mocks/engine.mock.go`... Done
Writing `FakeRTFSManager` to `manager.mock.go`... Done
```

since `counterfeiter` doesnt seem to offer a version command it's a little hard to verify what happens when it's installed in gopath and in modules, but it seems to me rather counterintuitive if `go run` does use modules if a package isn't available generally in GOPATH, but doesn't when it is (at least I would hope so)

**Comment by myitcv** [comment]
@joefitzgerald 

> go run will not use the version specified in the go.mod when invoked from a working directory inside a module

`go run` _does_ use the main module (i.e. `go.mod`) for all package/module resolution. 

The only reason `gobin` exists with respect to `go run` is that `go run` intentionally re-runs the link step and does not cache the resulting binary. This means `go run X` is going to be (much) slower than simply running an installed binary, which is what `gobin` does (plus a tiny bit of cache-based resolution which will get even faster in Go 1.13).

The cost of `go run` starts to add up if:

* you have lots of `go:generate` directives
* you run `go generate` (or equivalent) as part of your development cycle, i.e. on ~ each save 

More details in https://github.com/myitcv/gobin/wiki/FAQ#why-have-you-created-gobin

**Comment by joefitzgerald** [comment]
Thank you @myitcv and @bobheadxi for correcting my understanding. 🎉 that `go run` uses `go.mod` for version selection when in a module.

Sounds like I need to adjust some of the README content to better articulate that you can use `go run`, and optionally use `gobin` to speed up execution for multiple invocations in a module.

**Comment by joefitzgerald** [comment]
@bobheadxi hopefully https://github.com/maxbrunsfeld/counterfeiter/commit/f7bde7cbdb1288611466a0d715b1bbc956519eb1 is a bit more clear.

**Comment by bobheadxi** [comment]
Thank you @myitcv and @joefitzgerald ! The clarification on the upsides of `gobin` was helpful as well.
