### ISSUE TITLE
Imports not handled correctly for inline struct payloads

### ISSUE THREAD

**Issue by chrusty** [maxbrunsfeld/counterfeiter#128]
I've encountered an issue when generating mocks for an interface that uses an inline struct as a parameter.

Consider this interface:
```golang
package cruft

import (
	"context"
	"net/http"
	"time"
)

type Cruft interface {
	DoSomething(ctx context.Context, body struct {
		SomeString        string
		SomeStringPointer *string
		SomeTime          time.Time
		SomeTimePointer   *time.Time
		HttpRequest       http.Request
	}) error
}
```

It generates broken code (no import of the time or http packages, and the type name for the time / http fields are missing the package names):
```golang
type FakeCruft struct {
	DoSomethingStub func(context.Context, struct {
		SomeString        string
		SomeStringPointer *string
		SomeTime          Time
		SomeTimePointer   *Time
		HttpRequest       Request
	}) error
	doSomethingMutex       sync.RWMutex
	doSomethingArgsForCall []struct {
		arg1 context.Context
		arg2 struct {
			SomeString        string
			SomeStringPointer *string
			SomeTime          Time
			SomeTimePointer   *Time
			HttpRequest       Request
		}
	}
```

The result is generated code that won't compile!

I couldn't find any issues relating to this (closed or open). Also I've tested this with all of the historical versions and the behaviour hasn't changed.

Please let me know if you'd like any more detail.

**Comment by chrusty** [comment]
OK I spent some time looking through how counterfeiter works, enabled debug mode, and found that `*types.Struct` are unhandled. I raised a PR which actually fixes the issue, and includes a sample interface in the fixtures package.

The existing unit tests generate fakes for everything in that package, so broken code would be caught by the existing suite.

**Comment by joefitzgerald** [comment]
Thanks for the PR @chrusty; it has been merged and as a result this issue is fixed.
