### ISSUE TITLE
only log errors

### ISSUE THREAD

**Issue by cryptix** [maxbrunsfeld/counterfeiter#14]
hi,

i think it's cleaner to just output error messages and discard logs ala `Wrote A to a.go`.
It should be self evident by the exit code being zero that everything went fine.

**Comment by maxbrunsfeld** [comment]
This tool is primarily meant for humans to use; it's more akin to `wget` than `curl`. I'd merge a PR that adds some kind of `--quiet` option, but I like giving the user some feedback as to what happened, and I don't see much of a problem w/ printing it out.

**Comment by tjarratt** [comment]
Closing this for now, but if anyone feels strongly about this issue, I'd love to hear from you!

I'm generally inclined to agree with Max. It's good to know when your tools work. Having a tool that just silently writes files is a little too spooky for me.
