### ISSUE TITLE
Package mode is broken

### ISSUE THREAD

**Issue by nkovacs** [maxbrunsfeld/counterfeiter#140]
1. The error is ignored here: https://github.com/maxbrunsfeld/counterfeiter/blob/master/generator/fake.go#L137. Package generation actually fails, but you get a file with just the package clause and an empty comment.
2. The error is actually that the template calls `.Generate`, which is the Fake's Generate method, not the Generate template function.
3. After [fixing these](https://github.com/nkovacs/counterfeiter/commit/9606eb26be104f79828c698ced0154adee69948f), package mode still doesn't work correctly. The default value of OutputPath is "<input package name>shim", which is supposed to be a directory, and according to the [usage documentation](https://github.com/maxbrunsfeld/counterfeiter/blob/master/arguments/usage.go#L72), counterfeiter is supposed to generate two files into that directory: "<input package name>.go" for the interface and  "<input package name>shim.go" for the shim. Instead it creates a file at OutputPath, and puts both in there.

Side note: the documentation says `<output-path>` can be a directory or a file. For interface or function mode, it has to be a file. For package mode, it also currently has to be a file, but I don't know if that is intended or not. I also haven't tried older versions of counterfeiter in package mode, but if I remember correctly, the output path always had to be a file for interface or function mode.

**Comment by joefitzgerald** [comment]
@nkovacs thanks for your patience on this, I was able to use your suggested fixes, and correct the logic used for the output path. This will be released in `v6.4.1`.
