### ISSUE TITLE
Go 1.13 breaks proxy import

### ISSUE THREAD

**Issue by elgohr** [maxbrunsfeld/counterfeiter#143]
When running `go generate ./...` with Go 1.13 and fakes are not present, it tries to find the imported fakes (imported into the test files) as modules before generating the fakes and fails.
I don't know whether this is probably more a go issue (as adding *fakes into $GOPRIVATE doesn't work), but we should definitly get a workaround for that.

```go
Writing `FakeObjectStore` to `filesfakes/fake_object_store.go`... 
-: go: finding github.com/myApi/files latest
go: finding github.com/myApi latest
go: finding github.com/myApi/files/filesfakes latest
go build github.com/myApi/files/filesfakes: no Go files in 
exit status 1
```

**Comment by joefitzgerald** [comment]
Are you still experiencing this issue? Have you switched to using go modules? Does this fix your issue?

**Comment by elgohr** [comment]
Sorry, did forget about the issue. Everything fine in Go 1.15
