### ISSUE TITLE
Not able to install counterfeiter

### ISSUE THREAD

**Issue by adicocco** [maxbrunsfeld/counterfeiter#158]
Hello,

I'm trying to install counterfeiter using `go get -u github.com/maxbrunsfeld/counterfeiter` but I get following error
```
go: finding github.com/maxbrunsfeld/counterfeiter latest
go get github.com/maxbrunsfeld/counterfeiter: no matching versions for query "upgrade"
```

If I use counterfeiter using `go run github.com/maxbrunsfeld/counterfeiter/v6` it works fine.

My go env is 
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOENV="~/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="********"
GONOSUMDB="*********"
GOOS="darwin"
GOPATH="~/Developent/go"
GOPRIVATE="********"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="~/Developent/go/src/coligo/cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lj/fh8c9x112kbf4wxf6jqr7t5r0000gn/T/go-build949372732=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

And I'm using `go version go1.13.7 darwin/amd64`

Thank you

**Comment by joefitzgerald** [comment]
Please read [`Using counterfeiter`](https://github.com/maxbrunsfeld/counterfeiter#using-counterfeiter) from the README.

**Comment by plallin** [comment]
@adicocco try `go get github.com/maxbrunsfeld/counterfeiter/v6`

@joefitzgerald this issue is the second link on Google when someone searches "golang install counterfeiter"; it would be a better user experience to explain what's wrong and how to fix it, with links to the read me if needed
