### ISSUE TITLE
counterfeiter does not work via go generate if outside PATH

### ISSUE THREAD

**Issue by rittneje** [maxbrunsfeld/counterfeiter#166]
We do not have counterfeiter under our `PATH` env var. Instead, the location is determined by a `GOTOOLSPATH` env var. Until recently, the following `go:generate` directive worked fine:

```go
//go:generate ${GOTOOLSPATH}/bin/counterfeiter ...
```

However, with v6.2.3, this line no longer works. It seems counterfeiter is a complete no-op and doesn't return any errors. If I add it to `PATH` explicitly, then the following works as expected.

```go
//go:generate counterfeiter ...
```

**Comment by joefitzgerald** [comment]
The expansion of environments happens via go's `generate` functionality and unfortunately `counterfeiter` plays no role in resolution of itself.

I would recommend using the approach described in the `README` to invoke counterfeiter, described in detail here: https://github.com/maxbrunsfeld/counterfeiter#using-counterfeiter

This will result in addition of a `tools.go` file and your generate directives changing to look like this:

> `//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 <the arguments you use here>`

Using this approach, you won't need counterfeiter in your path or a tools path, and instead can use go.mod to control the version of counterfeiter you and the other members of your team use.

**Comment by rittneje** [comment]
@joefitzgerald This is definitely a bug with counterfeiter itself. I can tell from the debug output of go generate that it is properly executing the command with expansion. But the counterfeiter does nothing.

Based upon the recent release notes, my suspicion is that the fix for #137 (or something similar to it) is responsible. Why is counterfeiter even parsing go:generate directives? That makes no sense.

**Comment by joefitzgerald** [comment]
@rittneje have you tried to use the approach described in the README? This will solve your issues.

`counterfeiter` parses go:generate directives as  an optimization to speed up invocation when there are multiple generate directives in a package.

I will write a test that replicates your issue and look into a fix, as you are correct that the generate parsing logic should be able to handle this scenario.

**Comment by rittneje** [comment]
We have installed counterfeiter as a pre-built binary inside a docker container. I don't want to have to save the source code in the image or download it on the fly, so using `go run` as suggested will not work.

**Comment by joefitzgerald** [comment]
Are you using a `-generate` flag in your invocation of `counterfeiter`?

**Comment by joefitzgerald** [comment]
Also, could you please post the error output (if any) in the case of the failed invocation?

**Comment by rittneje** [comment]
No, we are not using that flag. We have the following forms:

```
// local interface
//go:generate $GOTOOLSPATH/bin/counterfeiter . MyInterface

// vendored interface
//go:generate $GOTOOLSPATH/bin/counterfeiter mypackage/vendor/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbiface.DynamoDBAPI

// standard library interface
//go:generate $GOTOOLSPATH/bin/counterfeiter os.FileInfo
```

On occasion, we also use the `-o` flag and/or `-fake-name` flag.

There is no output at all from the failed invocation. `go generate` also exits with a successful status code (i.e., 0).

**Comment by joefitzgerald** [comment]
If you are not using the `-generate` flag, counterfeiter is not doing parsing of the generate directives. Have you confirmed that the following results in different output?

`//go:generate $GOTOOLSPATH/bin/nonexistent`

**Comment by michaelbeaumont** [comment]
I'm running into this issue as well. If I have:
```
//go:generate counterfeiter -o fakes/fargate_client.go . FargateManager
```
everything works, if I have:
```
//go:generate "${GOBIN}/counterfeiter" -o fakes/fargate_client.go . FargateManager
```
it exits successfully but generates nothing.

**Comment by rittneje** [comment]
@joefitzgerald From tracing through the code, the bug was indeed caused by the changes in #137.

First, main calls `command.Detect` to get a list of "invocations".

`command.Detect` will return `invocations(cwd, generateMode)`, because `invokedByGoGenerate()` is true.

`invocations` will loop through all the files, calling `open(cwd, gofiles[i], generateMode)` on each and appending the resulting invocation lists.

`open` will call `matchForString` for each line the file.

Because of the regex changes in #137, `matchForString` now requires your `go:generate` directive to be one of the following:
1. `go run github.com/maxbrunsfeld/counterfeiter/v6`
2. `gobin -m -run github.com/maxbrunsfeld/counterfeiter/v6`
3. `counterfeiter`
4. `counterfeiter.exe`
Since `${GOTOOLSPATH}/bin/counterfeiter` doesn't match any of these, `matchForString` will return `nil`.

Consequently, `open` will return an empty slice, as will `invocations`, and `command.Detect`. Thus the `for` loop up in main will do nothing at all.

-----

Now, in terms of fixing this bug, I think counterfeiter should be amended not to have any of this fancy optimization logic under go generate. This is because you are actually violating how go generate is supposed to work. For example, I can pass a specific file path to go generate, and only directives in that file will be executed. Or I can pass a regex via -run, and only matching directives will be executed. But it seems in both cases counterfeiter will go behind my back and attempt to regenerate the entire package.
