### ISSUE TITLE
feature request: add flag to change generated fakes folder suffix

### ISSUE THREAD

**Issue by darwayne** [maxbrunsfeld/counterfeiter#172]
Hello,

First and foremost thank you so much for building this awesome tool; it simplifies my tests a great deal.

**Feature Request**
I noticed the `"fakes"` suffix is hardcoded for the generated folder; what are your thoughts on adding a flag that allows the user to optionally change that suffix?

At the moment my workaround is to specify the full path to the file

**Comment by joefitzgerald** [comment]
@darwayne you should now be able to specify a directory name (absolute `/the/path`, relative `path/to/dir` or bare `mycustomfakesdir`) and it will be respected for output. Thanks for identifying this issue! It will be released in `v6.4.1`.
