### ISSUE TITLE
Fails to generate interfaces with aliased sub-interfaces

### ISSUE THREAD

**Issue by mokiat** [maxbrunsfeld/counterfeiter#18]
Counterfeiter fails to generate fakes for the following interface types.

``` go
import alias "github.com/..../something"

type MyInterface interface {
  alias.ImportedInterface
}
```

If you change the `findImportPath` to the following piece of code, the problem is half way fixed.

``` go
func findImportPath(importSpecs []*ast.ImportSpec, alias string) string {
    for _, spec := range importSpecs {
        importPath := strings.Trim(spec.Path.Value, `"`)
        if path.Base(importPath) == alias {
            return importPath
        }
        if (spec.Name != nil) && (spec.Name.Name == alias) {
            return importPath
        }
    }
    return ""
}
```

However, imports are still messed up. I think the import section in the generated fake has the alias left in front, whereas the parameters in the methods of the aliased interface (as they are copy-pasted from the interface declaration file) don't have any alias. During `goimport` the import is considered unused and removed resulting in the fake not compiling.

**Comment by joefitzgerald** [comment]
This is fixed in [v6.0.0](https://github.com/maxbrunsfeld/counterfeiter/releases/tag/v6.0.0) of counterfeiter.
