### ISSUE TITLE
when multiple imports have the same name, counterfeiter does not alias any of them

### ISSUE THREAD

**Issue by karlkfi** [maxbrunsfeld/counterfeiter#19]
```
import (
    "net/http"
    "sync"

    "github.com/GoogleCloudPlatform/kubernetes/pkg/probe/http"
)
```

In this case, both are required, but one of them needs an alias. 
I thought this used to work, so it must be a regression.

**Comment by joefitzgerald** [comment]
This is now fixed in [v6.0.0](https://github.com/maxbrunsfeld/counterfeiter/releases/tag/v6.0.0); all imports are now aliased to avoid collisions.
