### ISSUE TITLE
Homebrew: Does not complete test on Go 1.20rc1

### ISSUE THREAD

**Issue by andig** [maxbrunsfeld/counterfeiter#221]
```
==> Testing counterfeiter
==> /home/linuxbrew/.linuxbrew/Cellar/counterfeiter/6.5.0_1/bin/counterfeiter -p os 2>&1
Writing `Os` to `osshim/os.go`... 
/home/linuxbrew/.linuxbrew/opt/go/libexec/src/os/file.go:246:27: StringData not declared by package unsafe
==> Testing counterfeiter (again)
==> /home/linuxbrew/.linuxbrew/Cellar/counterfeiter/6.5.0_1/bin/counterfeiter -p os 2>&1
Writing `Os` to `osshim/os.go`... 
/home/linuxbrew/.linuxbrew/opt/go/libexec/src/os/file.go:246:27: StringData not declared by package unsafe
Error: counterfeiter: failed
```

Refs https://github.com/Homebrew/homebrew-core/pull/117643

**Comment by billinghamj** [comment]
It looks like this issue remains in the final release of Go 1.20, and is failing in the release PR for Homebrew https://github.com/Homebrew/homebrew-core/pull/122082

**Comment by joefitzgerald** [comment]
@billinghamj  and @andig I cannot reproduce this issue. I have updated CI to run with 1.20 and the test suite passes fine. How is this being tested in the home-brew formula test suite?

**Comment by andig** [comment]
No longer sure either. Lets close this one.

**Comment by joefitzgerald** [comment]
See also: https://github.com/Homebrew/homebrew-core/pull/122082#pullrequestreview-1284087609

**Comment by andig** [comment]
Sounds closed or anyway discussion in progress. Thank you!
