### ISSUE TITLE
disable CircleCI

### ISSUE THREAD

**Issue by joefitzgerald** [maxbrunsfeld/counterfeiter#226]
Hey @maxbrunsfeld I need your help to disable the CircleCI project for `counterfeiter`. GitHub Actions suffices for now. https://app.circleci.com/settings/project/github/maxbrunsfeld/counterfeiter

**Comment by joefitzgerald** [comment]
@maxbrunsfeld can I get your help on this?

**Comment by maxbrunsfeld** [comment]
Ok, I stopped counterfeiter building on circle CI. Sorry for the delay there.
