### ISSUE TITLE
unused imports in generated files

### ISSUE THREAD

**Issue by pivotal-anova** [maxbrunsfeld/counterfeiter#23]
The fake seems to just copy all the import statements from the real file. We have a member of a value object in the real file that required an import, but which is not used anywhere in the fake. So we can't build after generating a fake for one of these files because the fake has an unused import we have to remove manually.

**Comment by tjarratt** [comment]
Closing since I'm not sure I can actually reproduce this issue.

**Comment by tjarratt** [comment]
Please re-open if you can help out by providing some reproduction steps or example code 😄
