### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [maxbrunsfeld/counterfeiter#248]
👋 it looks like 6.6.2 tag did not get marked as latest release, create this issue to raise some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/133721

**Comment by chenrui333** [comment]
cc @joefitzgerald

**Comment by joefitzgerald** [comment]
Fixed via https://github.com/maxbrunsfeld/counterfeiter/releases/tag/v6.6.2

**Comment by chenrui333** [comment]
@joefitzgerald somehow it is not get marked as latest release, can you mark it? Sorry about the hassle. Thanks!  🙏 
<img width="596" alt="image" src="https://github.com/maxbrunsfeld/counterfeiter/assets/1580956/c0bc301b-5d42-491c-8519-8e268546ad81">

**Comment by joefitzgerald** [comment]
It is marked as the latest release. My last comment coincided with me adding a release for the tag, and selecting the option to mark it as the latest release.

**Comment by joefitzgerald** [comment]
Scratch that; you're right, it somehow didn't mark it as latest despite me selecting that option.

**Comment by joefitzgerald** [comment]
Should be fixed now. Sorry for the confusion.
