### ISSUE TITLE
Include a dash -v flag on the counterfeiter command

### ISSUE THREAD

**Issue by zachgersh** [maxbrunsfeld/counterfeiter#27]
I was trying to figure out if I had the latest version of counterfeiter and was imaging that I could run something along the lines of

```
counterfeiter -v
```

Maybe I get a git sha back of the latest commit? A friendly version number would be nice but maybe I am asking too much?

**Comment by tjarratt** [comment]
Hey @zachgersh this is totally something I've wanted before.

Are you interested in submitting a PR for this?

**Comment by zachgersh** [comment]
Sure, did the SHA as version sound good or did we want to go with something else?

**Comment by tjarratt** [comment]
If that's expedient and makes the tool still work with "go get" then that's good for me. 

Sent From A Very Small Keyboard

**Comment by odlp** [comment]
It'd be great to see this version flag added. Our team is struggling with having different versions on Counterfeiter on different machines (and subsequently the different behaviour between versions as the tool evolves).

One approach could be using `-ldflags` during the build, [as detailed in this blog post](https://www.atatus.com/blog/golang-auto-build-versioning/). This could be populated with the git SHA. The difficulty in this approach is how to populate these arguments when a user is running `go get`. Does anyone know if golang has a mechanism to default build args?

Alternatively, could the version info could be committed in the source code and incremented per release? Like this [example](https://github.com/cloudfoundry/cli/blob/master/plugin_examples/call_cli_cmd/main/call_cli_cmd.go#L19:L23).

I'd be happy to help out with this. Is there a preference on the direction?

**Comment by chendrix** [comment]
Yes please

**Comment by chendrix** [comment]
I think making releases of counterfeiter more often, and attaching binaries to the github release could help alleviate this.

If we change the distribution mechanism from `go get` to downloading a binary from github, we can better handle versioning schemes, and provide actual versioning for counterfeiter.

**Comment by odlp** [comment]
@chendrix That sounds good. If the version number is committed in the source it wouldn't prevent people from using `go get` if they still wanted to.

**Comment by joefitzgerald** [comment]
Given that counterfeiter is now a `go module`, and we plan to use `semver` and tags to release versions, I believe this issue is solved. There is [an approach using `tools.go`](https://github.com/golang/go/issues/27653) that permits you to have take a module dependency on the tools your project uses, so that you can have reproducibility across machines.

Excerpt from https://github.com/golang/go/issues/27653:
```go
# create a new module
cd $(mktemp -d)
mkdir hello
cd hello
go mod init example.com/hello

# set GOBIN as a module-local install target
export GOBIN=$PWD/.bin

# update my PATH accordingly (I actually use https://github.com/cxreg/smartcd for this)
export PATH=$GOBIN:$PATH

# add a tool dependency (by definition, category 1 tool) following "best practice" laid out in 
# https://github.com/golang/go/issues/25922#issuecomment-412992431
cat <<EOD > tools.go
// +build tools

package tools

import (
        _ "golang.org/x/tools/cmd/stringer"
)
EOD

# install the tool
go install golang.org/x/tools/cmd/stringer

# verify we are using the module-local binary
which stringer

# which gives something like:
# /tmp/tmp.Hh0BNOF6k2/hello/.bin/stringer
```
