### ISSUE TITLE
missing the release notes for 6.10.0

### ISSUE THREAD

**Issue by chenrui333** [maxbrunsfeld/counterfeiter#302]
👋 looks like 6.10.0 release was not completed, ie a proper github release is missing. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/193500

**Comment by joefitzgerald** [comment]
Thanks, you're right. https://github.com/maxbrunsfeld/counterfeiter/releases/tag/v6.10.0 has been created.

**Comment by chenrui333** [comment]
Thanks @joefitzgerald!
