### ISSUE TITLE
Apply versioning tags to play nice with `gopkg.in`.

### ISSUE THREAD

**Issue by MrJoy** [maxbrunsfeld/counterfeiter#31]
... especially in light of breaking changes like #28.

Helpful for ensuring team doesn't get out of sync on tool versions.

**Comment by tjarratt** [comment]
This would be very nice to have -- would you be interested in submitting a PR for this, @MrJoy ?

**Comment by MrJoy** [comment]
Can git tags of existing commits actually be submitted as a PR?

This would be a policy change around releases, not a code change (I.E. not
Go build tags...).


-- 
Jon Frisby
Sent with Airmail

**Comment by MrJoy** [comment]
Specifically, you might consider:

```bash
git tag v1 733ce8507ced45a0e8ae8bb0331b538a69cb1433
git tag v2.0.0 a5a62e1d47c3d02bd0a46b57eddb11f60e9b1a48
git push --tags
```

**Comment by MrJoy** [comment]
Then, going forward you can tag releases, using the major version number to indicate compatibility-breaking changes.

**Comment by tjarratt** [comment]
Wow, this took me far too long to respond to. Your suggestion was spot on, and very helpful. Thank you so much, @MrJoy!

Closed by tagging some commits as v1 and v2
