### ISSUE TITLE
Test script handling of generated fixtures

### ISSUE THREAD

**Issue by tomwhoiscontrary** [maxbrunsfeld/counterfeiter#34]
Firstly, why is the output of the counterfeiting redirected to /dev/null? At one point, i broke counterfeiter so that it panicked when run, but because the output is thrown away, the test script gave me no clue as to what was going on. I think it would be more useful to let the output go to the console. It's a bit more verbose, but when counterfeiting works, only one line per package.

Secondly, the last line in the script cleans up arguments/argumentsfakes, but this is never created. Should it be, or can this line be removed?

Thirdly, the tests don't use the generated fakes. Rather, they use the checked-in fakes. Is this deliberate, and if so, is this wise?

If it is deliberate, then the test script is really doing two completely separate things: on the one hand, generating and compiling a set of fakes, which is a kind of smoke test, and on the other, running the tests. I think it would be helpful to rearrange the test script slightly to make this clearer; at present, it looks like the counterfeiting is setup for the tests, which is not the case.

If this is not deliberate, and the test script is supposed to be regenerating the checked-in fakes, then let's fix it!

Personally, i would suggest that the test script should regenerate the checked-in fakes. The way testing works at the moment is a bit weird; if i change the counterfeiting code, it's not enough to re-run the tests, or even the test script; i have to manually regenerate the fakes, and then run the tests. This seems scandalously error-prone - if i forget to re-generate the fakes, i can check in broken code, but have the build pass.

I'm happy to PR an updated script which fixes any of these problems.

**Comment by tjarratt** [comment]
Totally agree that it's strange that the test script is piping to /dev/null. I can only assume that was done once the tests mostly worked and it was frustrating to have to look at all of that output all the time. 

Since it's mostly there for travis and most contributors would probably run `go test ./...` or `ginkgo -r .` we can probably leave the test script more verbose and consider that a win.

**Comment by tjarratt** [comment]
Closed by merging #36.
