### ISSUE TITLE
Fakes handle nil slices incorrectly

### ISSUE THREAD

**Issue by tomwhoiscontrary** [maxbrunsfeld/counterfeiter#37]
In #33 i changed how slices are handled in fakes: they are copied, rather than stored by reference.

However, i forgot about nil. Because of the unique way Go represents slices, a nil pointer to a slice looks quite like an empty slice, and my copying code doesn't distinguish between them. Passing a nil to a fake leads to an empty slice being stored.

Sorry about this. I'll try to PR a fix for this later on today.

**Comment by maxbrunsfeld** [comment]
Thanks for following up on that, @tomwhoiscontrary.
