### ISSUE TITLE
packages in a directory with a hyphen in the last part, cause a Node.format error

### ISSUE THREAD

**Issue by esteban-herrera** [maxbrunsfeld/counterfeiter#39]
I have a package 'bar' defined in a project/foo-bar/bar.go

When trying to run counterfeit
`$ counterfeiter project/foo-bar Bar`
I get `format.Node internal error (1:12: expected ':' , found '-')`

This comes from line 59 in this file https://golang.org/src/go/format/format.go
I believe this is cause by the way the fake package name is created by parsing directories and package name.

The commit that introduced this behavior is 9db5229bab742fd6b9e0b4a27bd379c4fcbf0668

I plan on digging into it this weekend and making a PR, but feel free to beat me to it.

**Comment by tjarratt** [comment]
Thanks for submitting this issue Esteban! I'm sorry this broke recently. Maybe I've been moving too fast and breaking things in counterfeiter recently...

Would love a pull request if you find time, but I may beat you to the punch tonight. 

Sent From A Very Small Keyboard

**Comment by tjarratt** [comment]
Thanks again for letting us know about this bug @esteban-herrera. I was especially impressed, delighted and amazed that you successfully tracked it down to that one commit, that was very helpful.

Hope you continue to enjoy using counterfeiter!

**Comment by esteban-herrera** [comment]
Thanks for the quick fix! Glad I could help
