### ISSUE TITLE
counterfeiter drops numbers from my package

### ISSUE THREAD

**Issue by robdimsdale** [maxbrunsfeld/counterfeiter#40]
I have a package called `md5sum` with an interface `FileSummer`. When I run counterfeiter on that, it creates `md5sum/md5sumfakes/fake_file_summer.go` but the package inside that generated file is `mdsum` - counterfeiter dropped the `5` from the package name.

cc @tjarratt

**Comment by tjarratt** [comment]
Dang. 

Will try to fix this regression tonight. 

Thanks for catching that, Rob. 

Sent From A Very Small Keyboard

**Comment by tjarratt** [comment]
Closed by 068b14e
