### ISSUE TITLE
Generate counterfeiter fakes for stdlib interfaces

### ISSUE THREAD

**Issue by chendrix** [maxbrunsfeld/counterfeiter#46]
Often times we want to use interfaces that exist in the stdlib

Since counterfeiter requires you to point it at the source file which has the interface definition, this is pretty much impossible to do programatically, especially in go:generate comments

This would be a _huge_ win.

**Comment by chendrix** [comment]
We have figured out a way to create these kinds of fakes from the command line, in one-off fashions:

```
$ export GOPATH=/usr/local/Cellar/go/1.6.2/libexec/:$GOPATH
$ counterfeiter -o domainfakes/fake_net_conn.go /usr/local/opt/go/libexec/src/net/net.go Conn
Wrote `FakeConn` to `domainfakes/fake_net_conn.go`
```

Obviously we don't want to have to do this every single time.

**Comment by challiwill** [comment]
What's your expected UX here? You can put 
```
//go:generate counterfeiter -o domainfakes/fake_net_conn.go /usr/local/opt/go/libexec/src/net/net.go Conn
```
in one of your `.go` files and it will be generated in your fakes dir when you run `go generate ./...`.

I assume you'd want to not have to specify either destination or source file location, perhaps you'd want something like: 

```
//go:generate counterfeiter /src/net/net.go Conn
```
or
```
//go:generate counterfeiter net.Conn
```

**Comment by chendrix** [comment]
I think

//go:generate counterfeiter net.Conn

Would be wonderful.

I think there's a point to be made that maybe the scope of this issue should even be expanded to "allow generation of fakes for interfaces you don't own"

We've also attempted to do that for non-stdlib dependencies, and while if you're vendoring you can point to a source file in the vendor directory, the generated fake has incorrect import paths.

I think a unified solution would be great. If you can point to the source file use that, if you just specify a fully-qualified-package.interface, then it looks for it in your GOPATH?

**Comment by challiwill** [comment]
Yea that would be nice. 

Is there value in having the option to point to a source file also? It seems like the use case for this would be limited to when you are already importing the package, so a fully-qualified-package.interface would always be enough? There might be some challenges around accessing interfaces in imported packages with custom package names, I'm not sure.

**Comment by chendrix** [comment]
There's probably that. There might also be an inability to see definitions of unexported functions on interfaces if you're not doing source code parsing.

Can you write an interface that requires an implementor to implement a hidden method? That seems bonkers but I don't know if the parser complains.

**Comment by maxbrunsfeld** [comment]
> I think a unified solution would be great. If you can point to the source file use that, if you just specify a fully-qualified-package.interface, then it looks for it in your GOPATH?

This seems like a perfectly clean solution. @tjarratt, did you already do some work to move things in this direction?

**Comment by tjarratt** [comment]
I had tried initially to make `counterfeiter` easier to invoke from the command line, but have since settled on using the `go:generate` feature almost exclusively.

@challiwill I think it will be possible for you to implement something like `counterfeiter net.Conn` but I think you're going to run into some pain getting counterfeiter to save the files in the correct location (e.g.: closer to your project and NOT in the `GOROOT`).

I'm happy to help out however I can. This seems like it would be a small win for counterfeiter.

**Comment by tjarratt** [comment]
The only counterargument I can imagine is that it's (maybe?) considered good Go style to declare interfaces closer to your implementation. With respect to things in the standard library that might look like this...


```go
package stuff

import "net"

func DoStuffWithConn(conn MyConn) {
// TODO: actually write this code
}

type MyConn interface {
  net.Conn
}
```

However, this does lead to an explosive duplication of types, and results in indirection that may be undesirable or confusing.

**Comment by chendrix** [comment]
I don't even know if I agree that implementations should exist near their interface declaration.

How many reader implementations are there and in what packages?

**Comment by challiwill** [comment]
So I finally started looking into this. It turns out that counterfeiter has the behavior that given only one argument (eg `counterfeiter some-file.go`) it prompts the user for which interface to generate a fake for. Is this something that anyone uses? I was hoping to change the one argument case to be what we discussed above where `counterfeiter package.Interface` would generate a fake for the interface from the given package in the current fakes directory.

**Comment by chendrix** [comment]
I don't personally know of anyone who does use that, but I think the release that contains this work would have to be a major version bump anyways, so you're free to break backwards compatibility.

**Comment by challiwill** [comment]
I talked to a few people a no one knew it was a feature. I'm going to proceed for now with breaking it, and if it's determined we don't want to do that we can update that part of the code later.

**Comment by tjarratt** [comment]
I think I wrote that implementation a while ago and never got any traction on it. 

Most counterfeiter users (afaik) use the 'go generate' syntax so this should be fine. 

Sent From A Very Small Keyboard

**Comment by challiwill** [comment]
So I went with the following syntax as a fully qualified interface: 

`//go:generate counterfeiter net/http.ResponseWriter`

I realize mixing the import path style and interface access style is a little unconventional, but I hope it's intuitive enough.

**Comment by chendrix** [comment]
Thanks!
