### ISSUE TITLE
nil pointer dereference exception when generating fake

### ISSUE THREAD

**Issue by chrisdostert** [maxbrunsfeld/counterfeiter#64]
Generating fakes for any interface including [src-d/go-git/CloneOptions](https://github.com/src-d/go-git/blob/master/options.go#L31) as a method parameter results in the following nil pointer dereference:

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52c3b2]

goroutine 1 [running]:
github.com/maxbrunsfeld/counterfeiter/astutil.InjectAlias.func1(0x70be00, 0xc420156880, 0x70bf01)
        /go/src/github.com/maxbrunsfeld/counterfeiter/astutil/mutator.go:9 +0x132
go/ast.inspector.Visit(0xc420162340, 0x70be00, 0xc420156880, 0x70b700, 0xc420162340)
        /usr/local/go/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x70b700, 0xc420162340, 0x70be00, 0xc420156880)
        /usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0x70b700, 0xc420162340, 0x70be40, 0xc420158570)
        /usr/local/go/src/go/ast/walk.go:84 +0x156
go/ast.Walk(0x70b700, 0xc420162340, 0x70bec0, 0xc4201558c0)
        /usr/local/go/src/go/ast/walk.go:165 +0x2473
go/ast.Inspect(0x70bec0, 0xc4201558c0, 0xc420162340)
        /usr/local/go/src/go/ast/walk.go:385 +0x4b
github.com/maxbrunsfeld/counterfeiter/astutil.InjectAlias(0xc4201558c0, 0xc420158c00, 0xc420158c90)
        /go/src/github.com/maxbrunsfeld/counterfeiter/astutil/mutator.go:23 +0x94
github.com/maxbrunsfeld/counterfeiter/generator.CodeGenerator.fixup(0x7ffd9dd7ce28, 0x4, 0xc420164030, 0x1, 0x1, 0xc42004a708, 0x29, 0xc420012970, 0x4, 0x1, ...)
        /go/src/github.com/maxbrunsfeld/counterfeiter/generator/generator.go:202 +0x80
github.com/maxbrunsfeld/counterfeiter/generator.CodeGenerator.buildASTForFake(0x7ffd9dd7ce28, 0x4, 0xc420164030, 0x1, 0x1, 0xc42004a708, 0x29, 0xc420012970, 0x4, 0x1, ...)
        /go/src/github.com/maxbrunsfeld/counterfeiter/generator/generator.go:61 +0x199
github.com/maxbrunsfeld/counterfeiter/generator.CodeGenerator.GenerateFake(0x7ffd9dd7ce28, 0x4, 0xc420164030, 0x1, 0x1, 0xc42004a708, 0x29, 0xc420012970, 0x4, 0x1, ...)
        /go/src/github.com/maxbrunsfeld/counterfeiter/generator/generator.go:29 +0xa2
main.generateFake(0x7ffd9dd7ce28, 0x4, 0xc42004a700, 0x31, 0x0, 0x0, 0xc42004a800, 0x39, 0xc42004a82d, 0x4, ...)
        /go/src/github.com/maxbrunsfeld/counterfeiter/main.go:64 +0x1dc
main.main()
        /go/src/github.com/maxbrunsfeld/counterfeiter/main.go:43 +0x29f
util/vgit/vGit.go:3: running "counterfeiter": exit status 2

```

**Comment by tjarratt** [comment]
Hey @chrisdostert this is pretty interesting, I tried pretty hard to reproduce this with Golang 1.8.1 on Mac OS X but couldn't.

I created this repository to attempt to reproduce this in isolation, perhaps you could take a look and help me reproduce it?

https://github.com/tjarratt/counterfeiter-64-repro

* git clone https://github.com/tjarratt/counterfeiter-64-repro
* cd counterfeiter-64-repo
* ./test.sh

The test script installs the latest counterfeiter, then counterfeits an interface and runs a golang `testing` test against the generated fake. Please try that out and let me know what happens.

**Comment by tjarratt** [comment]
Any luck reproducing this, @chrisdostert ?

**Comment by chrisdostert** [comment]
@tjarratt  thanks so much for putting this together; i've put in a quick edit to demonstrate the break. Cheers

**Comment by tjarratt** [comment]
Well dang, that totally reproduces.

Thanks Chris! I'll take a look at fixing this.

**Comment by tjarratt** [comment]
Rad, that was actually pretty easy to resolve once I dug into the issue. Turns out we had a really silly null pointer dereference that we'd probably be able to catch more easily if we had a linter enabled on the project. 

It was extremely easy to write a test case for this from the reproduction steps you gave me. Thank you so much for the help, and for your patience.

Would you try installing version 4.1 of counterfeiter* and let me know if that's any better?

\* either of the following should work:
* `go get -u github.com/maxbrunsfeld/counterfeiter`
* `go get gopkg.in/maxbrunsfeld/counterfeiter/v4.1 && go install github.com/maxbrunsfeld/counterfeiter`

**Comment by chrisdostert** [comment]
Good show, works great; thank you so much!
