### ISSUE TITLE
Examples for changing output using -o don't seem to work

### ISSUE THREAD

**Issue by ryanwalls** [maxbrunsfeld/counterfeiter#65]
The help manual for counterfeiter prints:
```
OPTIONS
	-o
		Path to the file or directory for the generated fakes.
		This also determines the package name that will be used.
		By default, the generated fakes will be generated in
		the package "xyzfakes" which is nested in package "xyz",
		where "xyz" is the name of referenced package.
```

I tried using `-o` without success.  Here's what I did:

I have an interface in `packageA` named `MyInterface`.

From the root of my project, I run:
```
counterfeiter -o ./fakes MyInterface ./packageA
```

And the output is:
```
No such file or directory ''
```

I tried many other variations and couldn't get any to work.  Suggestions?

**Comment by tjarratt** [comment]
That's frustrating, sorry you had trouble with this @ryanwalls. In general, the syntax for `counterfeiter` should always be like this:

`counterfeiter [options] path/to/your/file.go YourInterface`

I'll update the docs for now, but this really smells to me like we could use some better tooling to generate correct help output.

**Comment by tjarratt** [comment]
Thanks for taking the time to submit this issue. It might seem like a small action to you, but it meant a lot to me:

1) I don't often hear directly from counterfeiter users. It brings me delight to hear when someone is using counterfeiter.
2) We don't often get bug reports when things are confusing or strange. This helps us improve the software!

So thank you!

**Comment by tjarratt** [comment]
Fixed at edge of master (so you can `go get -u github.com/maxbrunsfeld/counterfeiter`, but if you prefer to use gopkg.in you can also just install v4: http://gopkg.in/maxbrunsfeld/counterfeiter.v4

`go get gopkg.in/maxbrunsfeld/counterfeiter.v4`

**Comment by ryanwalls** [comment]
Thanks @tjarratt.  Yeah, I just switched our company to counterfeiter from mockery, and I really like it so far.  👍 

Will try out the new documentation and see if it helps.

**Comment by ryanwalls** [comment]
FYI, I really like https://github.com/spf13/cobra for command line handling.  Prints really handy help files.

**Comment by ryanwalls** [comment]
Yep, new documentation and implementation is good.  Was able to generate fakes in a special directory.  👍
