### ISSUE TITLE
-o option is ignored when source-path is not specified

### ISSUE THREAD

**Issue by nkovacs** [maxbrunsfeld/counterfeiter#70]
This doesn't work, it ignores the -o option:

```
 counterfeiter -o fakeSomething.go some/imported/package.Something
```

The problem is that this line is in the if branch: https://github.com/maxbrunsfeld/counterfeiter/blob/master/arguments/parser.go#L51

Is there a reason for this? I moved this line outside the if, and it seems to work fine.

Edit: there's already a pull request for this: #67

**Comment by tjarratt** [comment]
@nkovacs looks like we should be able to close this now - can you confirm this is working as you would expect ?

**Comment by nkovacs** [comment]
Yes, thanks
