### ISSUE TITLE
counterfeiter does not check vendor directory when generating using import path

### ISSUE THREAD

**Issue by nkovacs** [maxbrunsfeld/counterfeiter#75]
When you have a vendored library in your project and you use a fully qualified import path to generate a fake, counterfeiter won't search for it in the vendored directory.

E.g.:

```
mkdir -p vendor/foo/bar/baz/
echo "package baz\ntype Baz interface {\nBaz() string\n}\n" > vendor/foo/bar/baz/baz.go
counterfeiter foo/bar/baz.Baz

Package 'foo/bar/baz' not found on GOPATH
```

**Comment by tjarratt** [comment]
So if I understand the use case correctly here ...

There is a vendored library in your project, and it exports an interface. It's their interface that you want to generate a fake for?

**Comment by nkovacs** [comment]
Yes.

**Comment by tjarratt** [comment]
and just a quick note on the PR for this, #76 - I think this could be useful for other people, but I'm a little concerned about the difficulty of maintaining these changes.

Are you interested in backfilling some unit tests for the changes to the `locator` package for PRs #74 and #76 ?

**Comment by nkovacs** [comment]
You're right, it would become more complex, but on the other hand, having it find the package in `$GOPATH/src` when you're using vendoring is also confusing, and if you have an older, incompatible version of a library in `$GOPATH/src`, counterfeiter would create the fake, but it wouldn't build, and it wouldn't be obvious why counterfeiter is generating the wrong fake.

I'll try to write some tests, but I don't know when I'll have time to do that. For now I've forked counterfeiter, because I need these fixes for a project I'm working on.

**Comment by sysradium** [comment]
Is there any progress in solving this?

**Comment by chendrix** [comment]
Yeah I'd definitely love this behavior :)

**Comment by cholick** [comment]
Just ran into this issue and your suggested type alias workaround isn't a solution. In my case, I'm pulling in two difference dependencies whose interfaces interact.

**Comment by akshaymankar** [comment]
Here is an ugly workaround to this problem:
```
//go:generate counterfeiter -o ./fakes/fake_interface.go ../vendor/github.com/user/library/pkg Interface
//go:generate gsed -i "s|<my-pkg>/vendor/||g" fakes/fake_interface.go
```

After this running `go generate ./...` will generate the right fakes.

Note: gsed only works on osx (when gnu-sed is installed), if you want this to work on linux, use sed.

**Comment by joefitzgerald** [comment]
I think this will be fixed by #94, please check out that PR.

**Comment by nkovacs** [comment]
This does not seem to be working as expected.

Counterfeiter now uses `golang.org/x/tools/go/packages`, which does not resolve vendored packages correctly for me. I have to specify the full vendored path, e.g. `github.com/someuser/someproject/vendor/github.com/someotheruser/somelibrary.SomeType`. If I specify `github.com/someotheruser/somelibrary.SomeType`, it'll fail if it's not in GOPATH, and if it's in GOPATH, I believe it will use that version, which is also incorrect.

**Comment by nkovacs** [comment]
This is an issue with go/packages, there's workaround: https://github.com/golang/go/issues/30289
