### ISSUE TITLE
Strange GOPATH behavior in docker

### ISSUE THREAD

**Issue by viruslobster** [maxbrunsfeld/counterfeiter#77]
If your GOPATH contains multiple directories the order in which they appear seems to matter. I'm running this in a docker container (golang:latest) with my `GOPATH=/root/go:/usergo` and then trying to run counterfeiter on a file in `/usergo` (usergo is a mounted volume from the host machine). I get a `Could not find interface` error from counterfeiter. But if I follow the exact same steps with my GOPATH set to `/usergo:/root/go` then everything works fine.

I can't reproduce this on my local machine but this behavior is consistent on golang:latest

**Comment by tjarratt** [comment]
Strange. That sounds like it should be supported. From what I recall, counterfeiter respects the GOPATH and tries to find the first instance that matches. 

I'll see if I can find some time to dig into this.  

Sent From A Very Small Keyboard

**Comment by tjarratt** [comment]
@viruslobster is it possible you could post a dockerfile where this behavior is reproducible ?

**Comment by tjarratt** [comment]
Closing as unreproducible. *Please* do not hesitate to open a new issue should this start happening again.
