### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by elgohr** [maxbrunsfeld/counterfeiter#91]
Having a look at  pull requests from a year ago, I've got the impression that the maintenance of the library is not really what it should be (compared to the distribution).
I would volunteer to care for it as a contributer.
Otherwise I would like to fork the counterfeiter, due to I want it to be living.

**Comment by joefitzgerald** [comment]
@elgohr we have added two new maintainers; @zmb3 and I. I would love to get your help with the library, please feel free to make PRs and I will ensure they are reviewed 👀quickly.

Initially, we plan to add go module support, by making use of [`go/packages`](https://github.com/golang/tools/tree/master/go/packages). Then we plan to go through the open PRs and determine if the switch to go/packages has resolved them or not, and figure out a path forward for each.
