### ISSUE TITLE
Package name collisions

### ISSUE THREAD

**Issue by xanderflood** [maxbrunsfeld/counterfeiter#95]
I tried to counterfeit an interface in a package called `.../.../sync`, and the generated fake wouldn't build because the packages were not properly aliased, and conflicted with `"sync"`. For some reason, I noticed that the generator will attach a trivial alias to the target package, which causes it not to get aliased. By commenting out this line (`generator.go:139`) everything works properly and counterfeiter generates an alias for the target package so that it doesn't conflict with `sync`.

**Comment by xanderflood** [comment]
Details can be found in [this fork](https://github.com/xanderflood/counterfeiter).

**Comment by joefitzgerald** [comment]
The fix for this is released in [v6.0.1](https://github.com/maxbrunsfeld/counterfeiter/releases/tag/v6.0.1).
